language: bash

before_install:
  - sudo apt-get update && sudo apt-get install -y shellcheck jq curl
  - sudo apt-get install imagemagick
  
  - wget https://c4pr1c3.github.io/LinuxSysAdmin/exp/chap0x04/worldcupplayerinfo.tsv

  - wget https://c4pr1c3.github.io/LinuxSysAdmin/exp/chap0x04/web_log.tsv.7z
  - sudo apt install p7zip-full
  - 7z x web_log.tsv.7z


script:
  - ls -l
  - bash test.sh
  - cd chap0x04
    #任务一处理图片
  - bash task1.sh --help        #支持命令行参数方式使用不同功能
  - bash task1.sh -d ./Pic/testPic/ -j 45       #对jpeg格式图片进行图片质量压缩
  - bash task1.sh -d ./Pic/testPic/ -c 100      #对jpeg/png/svg格式图片在保持原始宽高比的前提下压缩分辨率
  - bash task1.sh -d ./Pic/testPic/ -e "hello"  #对图片批量添加自定义文本水印
  - bash task1.sh -d ./Pic/testPic/ -p "pre"    #批量重命名（统一添加文件名前缀或后缀，不影响原始文件扩展名）
  - bash task1.sh -d ./Pic/testPic/ -s "suffix"
  - bash task1.sh -d ./Pic/testPic/ -v          #将png/svg图片统一转换为jpg格式图片

    #任务二处理世界杯球员数据
  - bash task2.sh

    #任务二处理计算机访问数据
  - bash task3.sh --help        #查看帮助文档
  - bash task3.sh -d web_log.tsv -h 100         #统计访问来源主机TOP 100和分别对应出现的总次数
  - bash task3.sh -d web_log.tsv -i 100         #统计访问来源主机TOP 100 IP和分别对应出现的总次数
  - bash task3.sh -d web_log.tsv -u 100         #统计最频繁被访问的URL TOP 100
  - bash task3.sh -d web_log.tsv -r             #统计不同响应状态码的出现次数和对应百分比
  - bash task3.sh -d web_log.tsv -x 100         #分别统计不同4XX状态码对应的TOP 10 URL和对应出现的总次数
  - bash task3.sh -d web_log.tsv -l "/images/NASA-logosmall.gif"        #给定URL输出TOP 100访问来源主机
  
  - ls -l
  - pwd

notifications:
  email:
    on_success: never
